# Generated by Django 3.2 on 2021-04-17 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mytask', '0004_alter_task_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='phone_no',
            field=models.ImageField(default=0, max_length=10, upload_to=''),
        ),
    ]
