# Generated by Django 3.2 on 2021-04-18 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mytask', '0006_alter_task_phone_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='image',
            field=models.ImageField(default='', upload_to='images'),
        ),
    ]
